apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.hostname }}
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx
    kubernetes.io/ingress.allow-http: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: 250m
    nginx.org/client-max-body-size: 250M
    nginx.org/proxy-body-size: 250M

spec:
  tls:
  - hosts:
    -  {{ .Values.hostname }}
    secretName: {{ .Values.hostname }}
  rules:
  - host: {{ .Values.hostname }}
    http:
      paths:
      - path: /
        backend:
         serviceName: {{ .Values.service }}
         servicePort: 80
