apiVersion: extensions/v1beta1
kind: Deployment
metadata:
      name: sql-proxy
      app.kubernetes.io/name: sql-proxy
      app.kubernetes.io/instance: {{ .Release.Name }}

spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        name: sql-proxy-pod 
    spec:
      containers:
        # Change [INSTANCE_CONNECTION_NAME] here to include your GCP
        # project, the region of your Cloud SQL instance and the name
        # of your Cloud SQL instance. The format is
        # $PROJECT:$REGION:$INSTANCE
        # Insert the port number used by your database.
        # [START proxy_container]
        - image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          name: cloudsql-proxy
          resources:
            requests:
              cpu: 50m

          command: ["/cloud_sql_proxy", "--dir=/cloudsql",
                    "-instances={{ .Values.cloudsqlhost}}=tcp:0.0.0.0:3306",
                    "-credential_file=/secrets/cloudsql/credentials.json"]
          volumeMounts:
            - name: cloudsql-instance-credentials
              mountPath: /secrets/cloudsql
              readOnly: true
            - name: cloudsql
              mountPath: /cloudsql
          ports:
            - containerPort: 3306
              name: sql
        # [END proxy_container]
      # [START volumes]
      volumes:
        - name: cloudsql-instance-credentials
          secret:
            secretName: cloudsql-instance-credentials
        - name: cloudsql
          emptyDir:
