apiVersion: v1
kind: Service
metadata:
  name: sql
  labels:
    app.kubernetes.io/name: sql
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: ClusterIP
  ports:
    - port: 3306
      targetPort: 3306
      protocol: TCP
      name: sql
  selector:
    name: sql-proxy-pod
