apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.name }}-wiki-pod
  template:
    metadata:
      labels:
        app: {{ .Values.name }}-wiki-pod 
    spec:
      containers:
        - image: {{ .Values.repo }}/{{.Values.image}}
          imagePullPolicy: Always
          name: {{ .Values.name }}-pod
          env:
            - name: DB_HOST
              value: {{ .Values.name }}-{{ .Values.uuid }}-mysql
            - name: DB_TYPE
              value: mysql
            - name: DB_PORT
              value: "3306"
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.name }}-mysql-secret
                  key: mysql-user
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.name }}-mysql-secret
                  key: mysql-password
            - name: SITENAME
              value: {{ .Values.url }}
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.name }}-mysql-secret
                  key: mysql-database
          ports:
            - containerPort: 3000
              name: wiki
          resources:
            requests:
              cpu: 100m
          livenessProbe:
           httpGet:
             path: /
             port: 3000
             httpHeaders:
             - name: X-Custom-Header
               value: Awesome
           initialDelaySeconds: 180
           periodSeconds: 3
          readinessProbe:
           httpGet:
             path: /
             port: 3000
             httpHeaders:
             - name: X-Custom-Header
               value: Awesome
           initialDelaySeconds: 180
           periodSeconds: 3
