kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: "{{ .Values.url }}"
  annotations:
    cert-manager.io/cluster-issuer: "http"
    kubernetes.io/tls-acme: "true"
    traefik.ingress.kubernetes.io/router.entrypoints: websecure,web
    {{- range $key, $topping := (default dict (default dict .Values.hosting).tags) }}
    {{ $key }}: {{ $topping }}
    {{- end }}
spec:
  ingressClassName: traefik
  tls:
  - hosts:
    - {{ .Values.url }}
    secretName: {{ .Values.url }}
  rules:
  - host: {{ .Values.url }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.name }}-service
            port:
              number: 80
