apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.name }}-matomo
  template:
    metadata:
      labels:
        app: {{ .Values.name }}-matomo 
    spec:
      containers:
        - image: {{.Values.image}}
          imagePullPolicy: Always
          name: {{ .Values.name }}
          env:
            - name: MATOMO_DATABASE_HOST
              value: '{{ .Values.dbhost}}'
            - name: MATOMO_DATABASE_USERNAME
              value: '{{ .Values.dbuser}}'
            - name: MATOMO_DATABASE_PASSWORD
              value: '{{ .Values.dbpass}}'
            - name: MATOMO_DATABASE_DBNAME
              value: '{{ .Values.dbname }}'
            - name: SITENAME
              value: '{{ .Values.url }}'
          ports:
            - containerPort: 80
              name: http
          resources:
            requests:
              cpu: 100m
          #livenessProbe:
          # httpGet:
          #   path: /healthz/index.html
          #   port: 80
          #   httpHeaders:
          #   - name: X-Custom-Header
          #     value: Awesome
          # initialDelaySeconds: 180
          # periodSeconds: 3
          #readinessProbe:
          # httpGet:
          #   path: /healthz/index.html
          #   port: 80
          #   httpHeaders:
          #   - name: X-Custom-Header
          #     value: Awesome
          # initialDelaySeconds: 180
          # periodSeconds: 3
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}-matomo
  labels:
    app: {{ .Values.name }}-matomo 
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: {{ .Values.name }}-matomo 