apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.name }}-moodle-pod 
  template:
    metadata:
      labels:
        app: {{ .Values.name }}-moodle-pod 
    spec:
      containers:
        - args:
          - --nginx.scrape-uri=http://127.0.0.1:80/basic_status
          image: nginx/nginx-prometheus-exporter
          imagePullPolicy: Always
          name: metrics
          ports:
          - containerPort: 9113
            name: metrics
            protocol: TCP
        - image: {{ .Values.image_base }}/{{.Values.image}}
          imagePullPolicy: Always
          name: moodle
          env:
            - name: DBHOST
              value: {{ .Values.dbhost}}:{{ .Values.dbport }}
            - name: REDIS
              value: {{ .Values.name}}-redis-service
            - name: PROTO
              value: {{ .Values.proto}}
            - name: DBUSER
              value: {{ .Values.name }}
            - name: DBPASS
              value: '{{ .Values.dbpass }}'
            - name: SITENAME
              value: {{ .Values.url }}
            - name: DB
              value: {{ .Values.name}}
          ports:
            - containerPort: 80
              name: moodle
          resources:
          {{ if eq .Values.resource "low" }}
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          {{ else if eq .Values.resource "medium" }}
            requests:
              memory: "256Mi"
              cpu: "500m"
            limits:
              memory: "512Mi"
              cpu: "1000m"
          {{ else if eq .Values.resource "high" }}
            requests:
              memory: "2048Mi"
              cpu: "1000m"
            limits:
              memory: "4096Mi"
              cpu: "2000m"
          {{ else if eq .Values.resource "custom" }}
            requests:
              memory: {{ .Values.memory }}
              cpu: {{ .Values.cpu }}
            limits:
              memory: {{ .Values.memory }}
              cpu: {{ .Values.cpu }}
          {{ end }}
          volumeMounts:
            - name: moodle-persistent-storage
              mountPath: /var/www/html/shared
          livenessProbe:
           httpGet:
             path: /healthz/index.html
             port: 80
             httpHeaders:
             - name: X-Custom-Header
               value: Awesome
           initialDelaySeconds: 180
           periodSeconds: 3
          readinessProbe:
           httpGet:
             path: /healthz/index.html
             port: 80
             httpHeaders:
             - name: X-Custom-Header
               value: Awesome
           initialDelaySeconds: 180
           periodSeconds: 3
      volumes:
        - name: moodle-persistent-storage
          persistentVolumeClaim:
            claimName: {{ .Values.name }}-moodle-disk
