apiVersion: batch/v1
kind: CronJob
metadata:
  name:  {{ .Values.name }}-cron
spec:
  schedule: "*/15 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: moodle-cron
            image: mattiashem/moodle-cron
            env:
              - name: SITE
                value: {{ .Values.name }}-service
              - name: PASSWORD
                value: {{ .Values.cronSecret }}
          restartPolicy: Never 
