apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Values.name }}-redis
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ .Values.name }}-redis-pod 
    spec:
      containers:
        - image: redis
          imagePullPolicy: Always
          name: {{ .Values.name }}-redis-pod
          ports:
            - containerPort: 6379
              name: redis
          resources:
            requests:
              cpu: 50m
