# Default values for wordpress.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
name: moodle
repo: elino
image: moodle:v4.4.0
#dbuser: moodle we use name instead
dbpass: password
proto: https
image_base: elino
url: demo.uggla.io
SSLPROXY: true
kubedomainname: appselinose
dbhost: main-mysql-master.code.svc
dbport: 3306
storage: 10Gi
storageClass: default
seedSource: https://storage.googleapis.com/elino-public-assets/sql/moodle/uggla_seed.sql
seed: "true"
adminPasswordSecret: mysql-cluster
adminPasswordSecretValue: ROOT_PASSWORD
cronUrl: https://storage.googleapis.com/elino-public-assets/sql/moodle/moodle-cron.tar.gz
cronSecret: moodle-cron


hosting:
  tags: 
    norh/deployname: moodle
    norh/resources: low
    norh/deploydate: date
    norh/userid: userid
    norh/id: idss
  id:
    - 1234-1234-22333
  repo: github.com/elino/helmrepo/moodle


resource: 
#Only for custom
cpu: 100m
memory: 128Mi