# Default values for wordpress.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
name: matte-moodle
repo: mattiashem
image: moodle:v1
dbuser: moodle
dbpass: password
proto: https
image_base: mattiashem
url: demo.utbild.se
SSLPROXY: true
kubedomainname: appselinose
dbhost: sql.sql.svc.cluster.local:3306


