apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.name }}-mautic 
  template:
    metadata:
      labels:
        app: {{ .Values.name }}-mautic 
    spec:
      containers:
        - image: {{ .Values.image_base }}/{{.Values.image}}
          imagePullPolicy: Always
          name: {{ .Values.name }}
          env:
            - name: MAUTIC_DB_HOST
              value: '{{ .Values.dbhost}}'
            - name: MAUTIC_DB_USER
              value: '{{ .Values.dbuser}}'
            - name: MAUTIC_DB_PASSWORD
              value: '{{ .Values.dbpass}}'
            - name: MAUTIC_DB_NAME
              value: '{{ .Values.dbname }}'
            - name: MAUTIC_RUN_CRON_JOBS
              value: 'true'
            - name: SITENAME
              value: '{{ .Values.url }}'
            - name: MAUTIC_TRUSTED_PROXIES
              value: '["0.0.0.0/0"]'
            - name: MAUTIC_URL
              value: {{ .Values.name }}-mautic
            - name: MAUTIC_ADMIN_EMAIL
              value: matte@elino.se
            - name: MAUTIC_ADMIN_PASSWORD
              value: "testAdminPassword3322!"
            - name: MAUTIC_ADMIN_USERNAME
              value: "adminuser"
            - name: MAUTIC_ADMIN_FIRSTNAME
              value: firstname
            - name: MAUTIC_ADMIN_LASTNAME
              value: lastname
            - name: MAUTIC_INSTALL_FORCE
              value: "true"
        
          ports:
            - containerPort: 80
              name: http
          resources:
            requests:
              cpu: 100m
          #livenessProbe:
          # httpGet:
          #   path: /healthz/index.html
          #   port: 80
          #   httpHeaders:
          #   - name: X-Custom-Header
          #     value: Awesome
          # initialDelaySeconds: 180
          # periodSeconds: 3
          #readinessProbe:
          # httpGet:
          #   path: /healthz/index.html
          #   port: 80
          #   httpHeaders:
          #   - name: X-Custom-Header
          #     value: Awesome
          # initialDelaySeconds: 180
          # periodSeconds: 3
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}-mautic
  labels:
    app: {{ .Values.name }}-mautic 
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: {{ .Values.name }}-mautic 