# Default values for the standalone ingress chart.
# Points an existing in-cluster Service at a public hostname.
hostname: example.eu-up.apps.robots.beer
service: myhostservice
port: 80

hosting:
  tags:
    norh/deployname: ingress
    norh/resources: low
    norh/deploydate: date
    norh/userid: userid
    norh/id: idss
