apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}-{{ .Values.uuid }}-pg-superuser
  annotations:
      {{-  range $key, $topping := $.Values.hosting.tags }}
      {{ $key }}: {{ $topping }}
      {{- end }}
type: Opaque
data:
  username: {{ "postgres" | b64enc }}
  password: {{ .Values.dbpass | b64enc }}
