kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Values.name }}-{{ .Values.uuid }}
  annotations:
      {{-  range $key, $topping := $.Values.hosting.tags }}
      {{ $key }}: {{ $topping }}
      {{- end }} 
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.storage }}
  storageClassName: {{ .Values.storageClass }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.name }}-{{ .Values.uuid }}
data:
  index.html: |
    <html>
    <head>
    <title>Health Check</title>
    </head>
    <body>
    <h1>Health Check</h1>
    </body>
    </html>


---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}-{{ .Values.uuid }}
  annotations:
      {{-  range $key, $topping := $.Values.hosting.tags }}
      {{ $key }}: {{ $topping }}
      {{- end }} 
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.name }}-{{ .Values.uuid }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}-{{ .Values.uuid }} 
 
    spec:
      containers:
        - command:
          - /bin/apache_exporter
          - --scrape_uri=http://127.0.0.1/server-status?auto
          image: lusotycoon/apache-exporter
          imagePullPolicy: Always
          name: metrics
          ports:
          - containerPort: 9117
            name: metrics
            protocol: TCP
        - image: {{.Values.image}}
          imagePullPolicy: Always
          name: wordpress
          env:
            - name: WORDPRESS_DB_HOST
              value: {{ .Values.dbhost }}
            - name: WORDPRESS_DB_USER
              valueFrom:
                 secretKeyRef:
                   name: {{ .Values.name }}-{{ .Values.uuid }}
                   key: SQL_USER
            - name: WORDPRESS_DB_PASSWORD
              valueFrom:
                 secretKeyRef:
                   name: {{ .Values.name }}-{{ .Values.uuid }}
                   key: SQL_PASSWORD
            - name: WORDPRESS_DB_NAME
              value: {{ .Values.dbname }}
            - name: WORDPRESS_TABLE_PREFIX
              value: {{ .Values.dbprefix }}
          ports:
            - containerPort: 80
              name: wordpress
          
          resources:
          {{ if eq .Values.resource "low" }}
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          {{ else if eq .Values.resource "medium" }}
            requests:
              memory: "256Mi"
              cpu: "500m"
            limits:
              memory: "512Mi"
              cpu: "1000m"
          {{ else if eq .Values.resource "high" }}
            requests:
              memory: "2048Mi"
              cpu: "1000m"
            limits:
              memory: "4096Mi"
              cpu: "2000m"
          {{ else if eq .Values.resource "custom" }}
            requests:
              memory: {{ .Values.memory }}
              cpu: {{ .Values.cpu }}
            limits:
              memory: {{ .Values.memory }}
              cpu: {{ .Values.cpu }}
          {{ end }}
          volumeMounts:
            - name: wordpress-persistent-storage
              mountPath: /var/www/html/wp-content/
            - name: health
              mountPath: /var/www/html/health/
            - mountPath: /usr/local/etc/php/conf.d/custom.ini
              name: wordpress-php-options
              subPath: wordpress.ini
            - mountPath: /etc/apache2/sites-enabled/000-default.conf
              name: apache-config
              subPath: 000-default.conf
          livenessProbe:
           httpGet:
             path: /health/index.html
             port: 80
             httpHeaders:
             - name: X-Custom-Header
               value: Awesome
           initialDelaySeconds: 3
           periodSeconds: 3
          readinessProbe:
           httpGet:
             path: /health/index.html
             port: 80
             httpHeaders:
             - name: X-Custom-Header
               value: Awesome
           initialDelaySeconds: 3
           periodSeconds: 3
      securityContext:
        fsGroup: 200
      volumes:
        - name: health
          configMap:
            name: {{ .Values.name }}-{{ .Values.uuid }}
        - name: wordpress-persistent-storage
          persistentVolumeClaim:
            claimName: {{ .Values.name }}-{{ .Values.uuid }}
        - configMap:
            defaultMode: 420
            name: word-php-{{ .Values.name }}-{{ .Values.uuid }}
          name: wordpress-php-options
        - configMap:
            defaultMode: 420
            name: apache-{{ .Values.name }}-{{ .Values.uuid }}
          name: apache-config
