kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Values.name }}{{ .Values.version }}-disk
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}{{ .Values.version }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.name }}{{ .Values.version }}-pod
  template:
    metadata:
      labels:
        app: {{ .Values.name }}{{ .Values.version }}-pod 
    spec:
      containers:
        - image: {{ .Values.image_base }}/{{.Values.image}}
          imagePullPolicy: Always
          name: {{ .Values.name }}{{ .Values.version }}-pod
          env:
            - name: DBHOST
              # Connect to the SQL proxy over the local network on a fixed port.
              # Change the [PORT] to the port number used by your database
              # (e.g. 3306).
              value: {{ .Values.dbhost }}
            # These secrets are required to start the pod.
            # [START cloudsql_secrets]
            - name: DBPASS
              value: '{{ .Values.dbpass }}'
            - name: SITENAME
              value: {{ .Values.name }}
          ports:
            - containerPort: 8000
              name: wordpress
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          volumeMounts:
            - name: wordpress-persistent-storage
              mountPath: /repo
          livenessProbe:
           httpGet:
             path: /healthz/index.html
             port: 8000
             httpHeaders:
             - name: X-Custom-Header
               value: Awesome
           initialDelaySeconds: 3
           periodSeconds: 3
          readinessProbe:
           httpGet:
             path: /healthz/index.html
             port: 8000
             httpHeaders:
             - name: X-Custom-Header
               value: Awesome
           initialDelaySeconds: 3
           periodSeconds: 3
      securityContext:
        fsGroup: 200
      volumes:
        - name: wordpress-persistent-storage
          persistentVolumeClaim:
            claimName: {{ .Values.name }}{{ .Values.version }}-disk
