---
{{ if .Values.redis.enabled }}

# Source: redis-cluster/templates/redis-svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: redis-{{ .Values.name }}-{{ .Values.uuid }}
spec:
  type: ClusterIP
  ports:
    - name: tcp-redis
      port: 6379
      targetPort: tcp-redis
  selector:
    app.kubernetes.io/name: redis-{{ .Values.name }}-{{ .Values.uuid }}
    app.kubernetes.io/instance: redis
---
# Source: redis-cluster/templates/redis-statefulset.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-{{ .Values.name }}-{{ .Values.uuid }}
  labels:
    app.kubernetes.io/name: redis-{{ .Values.name }}-{{ .Values.uuid }}
    app.kubernetes.io/instance: redis
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: redis-{{ .Values.name }}-{{ .Values.uuid }}
      app.kubernetes.io/instance: redis
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: redis-{{ .Values.name }}-{{ .Values.uuid }}
        app.kubernetes.io/instance: redis
      annotations:
        prometheus.io/port: "9121"
        prometheus.io/scrape: "true"
    spec:
      enableServiceLinks: false
      containers:
        - name: redis
          image: redis
          imagePullPolicy: "IfNotPresent"
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: REDIS_PORT
              value: "6379"
          ports:
            - name: tcp-redis
              containerPort: 6379
            - name: tcp-redis-bus
              containerPort: 16379
          resources:
            limits:
              memory: 2G
            requests:
              cpu: 250m
              memory: 1G
        - name: metrics
          image: docker.io/bitnami/redis-exporter:1.23.1-debian-10-r19
          imagePullPolicy: "IfNotPresent"
          command:
            - /bin/bash
            - -c
            - |
              redis_exporter
          env:
            - name: REDIS_ALIAS
              value: redis-{{ .Values.name }}-{{ .Values.uuid }}
            - name: REDIS_ADDR
              value: "redis://127.0.0.1:6379"
          ports:
            - name: http-metrics
              containerPort: 9121
{{ end }}
