apiVersion: v1
data:
  WP_USER: {{ .Values.wpuser }}
  WP_PASSWORD: {{ .Values.wppass }}
  SQL_PASSWORD: {{ .Values.dbuser }}
  SQL_USER: {{ .Values.dbpass }}
kind: Secret
metadata:
  annotations:
  name: {{ .Values.name }}-{{ .Values.uuid }}
type: Opaque