apiVersion: v1
data:
  WP_USER: {{ .Values.wpuser | b64enc  }}
  WP_PASSWORD: {{ .Values.wppass | b64enc }}
  SQL_PASSWORD: {{ .Values.dbpass | b64enc }}
  SQL_USER: {{ .Values.dbuser | b64enc }}
kind: Secret
metadata:
  annotations:
  name: {{ .Values.name }}-{{ .Values.uuid }}
type: Opaque
