apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}-{{ .Values.uuid }}
  labels:
    app: {{ .Values.name }}{{ .Values.version }}-pod
  annotations:
      prometheus.io/path: /metrics
      prometheus.io/port: "9117"
      prometheus.io/scrape: "true"
      {{-  range $key, $topping := $.Values.hosting.tags }}
      {{ $key }}: {{ $topping }}
      {{- end }} 
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: {{ .Values.name }}-{{ .Values.uuid }}