apiVersion: v1
kind: ConfigMap
metadata:
  name: word-php-{{ .Values.name }}-{{ .Values.uuid }}
data:
  wordpress.ini: |
    file_uploads = On
    memory_limit = 512M
    upload_max_filesize = 64M
    post_max_size = 64M
    max_execution_time = 600
    max_input_time = 1000 
    display_errors = Off
    zend_extension = opcache
    opcache.enable = 1
    allow_url_fopen = Off
    zlib.output_compression = On
    zlib.output_compression_level = 5
    realpath_cache_size = 16M
    realpath_cache_ttl = 120
    session.save_handler = files
    session.save_path = /var/lib/php/sessions
    session.cache_limiter = public
    session.cache_expire = 180
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: apache-{{ .Values.name }}-{{ .Values.uuid }}
data:
  000-default.conf: |
    LoadModule deflate_module modules/mod_deflate.so
    KeepAlive On
    # MaxKeepAliveRequests: How many requests to allow during a persistent connection.
    # You can set it 0 for unlimited requests, but it is not recommended.
    MaxKeepAliveRequests 100
    # KeepAliveTimeout: Number of seconds to wait for the next request from the
    # same client on the same connection. Default is 5 seconds
    KeepAliveTimeout 15
    <VirtualHost *:80>
        ServerAdmin webmaster@localhost
        ErrorLog ${APACHE_LOG_DIR}/error.log
        CustomLog ${APACHE_LOG_DIR}/access.log combined
      Alias /server-status /tmp/server-stats
      <Directory /tmp/server-status>
        SetHandler server-status
        Order allow,deny
        Deny from env=go_away
        Allow from all
     </Directory>
    # Keep track of extended status information for each request
    #ExtendedStatus On
    # Determine if mod_status displays the first 63 characters of a request or
    # the last 63, assuming the request itself is greater than 63 chars.
    # Default: Off
    #SeeRequestTail On
    <IfModule mod_proxy.c>
      # Show Proxy LoadBalancer status in mod_status
      ProxyStatus On
    </IfModule>
    <IfModule mod_deflate.c>
      AddOutputFilterByType DEFLATE application/javascript
      AddOutputFilterByType DEFLATE application/rss+xml
      AddOutputFilterByType DEFLATE application/vnd.ms-fontobject
      AddOutputFilterByType DEFLATE application/x-font
      AddOutputFilterByType DEFLATE application/x-font-opentype
      AddOutputFilterByType DEFLATE application/x-font-otf
      AddOutputFilterByType DEFLATE application/x-font-truetype
      AddOutputFilterByType DEFLATE application/x-font-ttf
      AddOutputFilterByType DEFLATE application/x-javascript
      AddOutputFilterByType DEFLATE application/xhtml+xml
      AddOutputFilterByType DEFLATE application/xml
      AddOutputFilterByType DEFLATE font/opentype
      AddOutputFilterByType DEFLATE font/otf
      AddOutputFilterByType DEFLATE font/ttf
      AddOutputFilterByType DEFLATE image/svg+xml
      AddOutputFilterByType DEFLATE image/x-icon
      AddOutputFilterByType DEFLATE text/css
      AddOutputFilterByType DEFLATE text/html
      AddOutputFilterByType DEFLATE text/javascript
      AddOutputFilterByType DEFLATE text/plain
      AddOutputFilterByType DEFLATE text/xml
    </IfModule>



    DocumentRoot /var/www/html
    </VirtualHost>