apiVersion: v1
kind: ConfigMap
metadata:
  name: portal
data:
  postal.yml: |
    general:
      # This can be changed to allow messages to be sent from multiple IP addresses
      use_ip_pools: false
    
    web:
      # The host that the management interface will be available on
      host: postal.yourdomain.com
      # The protocol that requests to the management interface should happen on
      protocol: http
    
    web_server:
      # Specify configuration for the Postal web server
      bind_address: 0.0.0.0
      port: 5000
    
    smtp_server:
      # Specify configuration to the Postal SMTP server
      port: 25
    
    logging:
      # Specify options for the logging
      stdout: true
    
    main_db:
      # Specify the connection details for your MySQL database
      host: {{ .Values.dbhost }}
      username: {{ .Values.dbuser }}
      password: {{ .Values.dbpass }}
      database: {{ .Values.dbname}}
    
    message_db:
      # Specify the connection details for your MySQL server that will be house the
      # message databases for mail servers.
      host: {{ .Values.dbhost }}
      username: {{ .Values.dbuser }}
      password: {{ .Values.dbpass }}
      database: {{ .Values.dbname}}
    
    rabbitmq:
      # Specify connection details for your RabbitMQ server
      host: {{ .Values.rqhost}}
      username: {{ .Values.rquser}}
      password: {{ .Values.rqpass}}
      vhost: {{ .Values.rqvhost}}
    
    dns:
      # Specify the DNS records that you have configured. Refer to the documentation at
      # https://github.com/atech/postal/wiki/Domains-&-DNS-Configuration for further
      # information about these.
      mx_records:
        {{ .Values.dns.mx_records }}
      smtp_server_hostname: {{ .Values.dns.smtp_server_hostname }}
      spf_include: {{ .Values.dns.spf_include }}
      return_path: {{ .Values.dns.return_path }}
      route_domain: {{ .Values.dns.route_domain }}
      track_domain: {{ .Values.dns.track_domain }}
    
    smtp:
      # Specify an SMTP server that can be used to send messages from the Postal management
      # system to users. You can configure this to use a Postal mail server once the
      # your installation has been set up.
      host: {{ .Values.smtp.host }}
      port: {{ .Values.smtp.port }}
      username: {{ .Values.smtp.username }}
      password: {{ .Values.smtp.password }}
      from_name: {{ .Values.smtp.from_name }}
      from_address: {{ .Values.smtp.from_address }}
    
    rails:
      # This is generated automatically by the config initialization. It should be a random
      # string unique to your installation.
      secret_key: {{ .Values.rails.secret_key }}
  signing.key: |
     -----BEGIN PRIVATE KEY-----
     MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCa0tgWvWkBz2Gb
     D8s/2mOcunkml1hj50WCGsKGojRywS7nXQl87Uh3zu8dGfCT0zybGZq1jYt6PcGG
     0rDFdqemqWUpdyW/4/FxCUwR0fRZn0/cLq8lwdGNHstSzeiDVh7/Sq5NC10MBewG
     cSa1yyoI9za0wYa+U1alKkOBc0Aq05FWKeYWynOJOSJuWViB6cvAV1TRv38PY6gW
     00Ed0vbbhpVNeYdsfXuBFCojN2GjM89IvhbzRpRtZRc7C5hUzWM6S95UphMe08Bk
     cUfXMAdt/lLMY9/LPQ4VUao5WEKhPofOcBBDcW5LnR8GovjsotbkBSA/WPtfdFlc
     sSD3mYCJAgMBAAECggEAA37VY10LIv/zPpCamIJWG6afn9oMpDPHX1a6k9bTa5BW
     PmG8ujnyuAa/YgcxBetf28oWErmDf8LnbMNyu4CQbCw4pRkkLGsJa1GICsJ0W3Yj
     888HhAkWUbLzaPcOY/G0sTOW0BU8uG3lTGdvVe0kca+gJ/BTGhawVvoHbGOlXBoh
     86pmElwdKxzTyW4Xae3cbXJpFX8SikMFQ9fPVF28DhGLwy4eBm46LjC6fq7r7CM1
     RbazlNlMHqQ1MUqy8SLR6hV45vucq56G+LpnopJMQS7FvgqDb35vaRXmHE1OaiSB
     UCEwkZyBBnEwWCOn24C8+hoEIDSrPHbu8bfC1/GMcQKBgQC5fwCS9u/jSFa78Zd5
     sImEr/Rs5LQNfNuDOb99nVBXvv8UhvHclFOKA21FsXC0gubS2x+F6P0mLLFUiUkp
     jyI4syFSL3MNQ9nCzBNWBfHxkVg3+/ecEaGeYMbacb2bncpqlWxz1J48WQIph6Mf
     BY1v+i5LiKGMNjtrELkKjfT8uQKBgQDVq17rOfJ6agUWAvl6ozg0q8MIeB+HZrRu
     gX6+phC/MmYCoPZ+C9+zLP+jutNEPwKgRFwDHUvhRrkF480/wwGk6SgVl+Km1EJy
     gqcymDk0xTjWAeISSMH4g8NKEV3t5POdFJf11Jx0ddhD96KpGyqvwnUaGS1P3XoA
     PiKurODaUQKBgDlBl2bFrBQmrwcCMnRQZpI7UaIPEfib0pH10EKwvSzoeonWgW9J
     pWOTXTZG5/f/88mf82H9Ia6X2wCyA5A9ax2/RQi+NrAggmXbYhiKazzaVTWqo6pb
     0tw1GQwyUYloMiOmDbzPIyyTeNRi1pnrt9WZjpKoEN1bnAmXNtaoLLeZAoGAL+WZ
     gntb6qsHdta13BLoj44NS0G6N50DR15J7izFxkZi7aXte3Xn8H9e0vIXV84UJZ8N
     TTltABPdd/+HzApHvRLzBFwm16TvPEIjfsj20eiABCEp71VV/gJzbZAVETXokkbC
     hb3iUIz2LM4/LU9Es1+Q5ofMS4HnTlSfa66fPPECgYEAj6+d2xjZTHKIQtQ4hUKG
     jBJ6Py4KRoaAb5jdchDQA+WDsZwBky1kC4D6cwX7jbSbJk9bfpeWSFvdu/FQMe8X
     vil6HFV1pdwoUG9hEc9bmbHpaUIHA74Fe2u/nRED+qAJiHgEcmSzoyKRuMssYEeO
     a5u7YGDkbABvTgUlISI07Oo=
     -----END PRIVATE KEY-----
