apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}-smtp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.name }}-smtp
  template:
    metadata:
      labels:
        app: {{ .Values.name }}-smtp
    spec:
      containers:
        - image: {{.Values.image}}
          imagePullPolicy: Always
          name: {{ .Values.name }}
          command: ["postal","smtp-server"]
          ports:
            - containerPort: 25
              name: stmp
          resources:
            requests:
              cpu: 100m
          volumeMounts:
            - name: config
              mountPath: "/config"
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: portal
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}-smtp
  labels:
    app: {{ .Values.name }}-smtp
spec:
  type: LoadBalancer
  ports:
    - port: 25
      targetPort: 25
      protocol: TCP
  selector:
    app: {{ .Values.name }}-smtp