apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployname }}-natsout
  labels:
    app: {{ .Values.deployname }}-natsout
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.deployname }}-natsout
  template:
    metadata:
      annotations:
        app: {{ .Values.deployname }}-natsout
      labels:
        app: {{ .Values.deployname }}-natsout
    spec:
      containers:
      - name: {{ .Values.deployname }}-natout
        image: "mattiashem/nats-client:{{ .Values.gitsha }}"
        imagePullPolicy: Always
        command: ["./lissenNats.sh"]
        env:
          - name: nats
            value: nats
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
      imagePullSecrets:
      - name: gitlab 


